version: "3.8"

services:
  api-gateway:
    build: ./backend/api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - user-service
      - appointment-service
      - payment-service
      - notification-service

  user-service:
    build: ./backend/user-service
    ports:
      - "8001:8001"

  appointment-service:
    build: ./backend/appointment-service
    ports:
      - "8002:8002"

  payment-service:
    build: ./backend/payment-service
    ports:
      - "8003:8003"

  notification-service:
    build: ./backend/notification-service
    ports:
      - "8004:8004"
